version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-movie-db
    environment:
      POSTGRES_DB: movie-management-db
      POSTGRES_USER: jabes
      POSTGRES_PASSWORD: sebaj
    ports:
      - "15432:5432"  # Mapeo del puerto para que tu aplicación pueda acceder a la base de datos
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

volumes:
  postgres_data:
